In [1]:
import pandas as pd
def cleanffball(year,name):
    url = f'https://www.pro-football-reference.com/years/{year}/fantasy.htm'
    df = pd.read_html(url,header=1)[0]
    df = df.drop(['Rk','Tm','VBD'],axis=1)
    df = df[df['FantPos'].notna()]
    df = df[df['FantPos'] != 'FantPos']
    df['Y/A'] = df['Y/A'].fillna(0)
    df['Y/R'] = df['Y/R'].fillna(0)
    df['2PM'] = df['2PM'].fillna(0)
    df['2PP'] = df['2PP'].fillna(0)
    df = df[df['FantPt'].notna()]
    df = df.replace('\+','',regex=True).astype(object)
    df = df.replace('\*','',regex=True).astype(object)
    columns = df.columns[2:]
    for col in columns:
        df[col] = pd.to_numeric(df[col],errors='coerce')
    df['N_PPR_OvRank'] = df['FantPt'].rank(method='first',ascending=False)
    df['PPR_OvRank'] = df['PPR'].rank(method='first',ascending=False)
    df = df.drop(columns=['OvRank'],axis=1)
    df = df.dropna()
    df['Year'] = year
    df.to_csv(f'{name}.csv',index=False)

In [2]:
years = [2021,2020,2019,2018,2017,2016,2015,2014,2013,2012]
for year in years:
    cleanffball(year,'season_' + str(year))

In [3]:
season_21 = pd.read_csv('season_2021.csv')
season_20 = pd.read_csv('season_2020.csv')
season_19 = pd.read_csv('season_2019.csv')
season_18 = pd.read_csv('season_2018.csv')
season_17 = pd.read_csv('season_2017.csv')
season_16 = pd.read_csv('season_2016.csv')
season_15 = pd.read_csv('season_2015.csv')
season_14 = pd.read_csv('season_2014.csv')
season_13 = pd.read_csv('season_2013.csv')
season_12 = pd.read_csv('season_2012.csv')
seasons_L10Y = pd.concat([season_21,season_20,season_19,season_18,season_17,season_16,season_15,season_14,season_13,season_12], ignore_index=True)
seasons_L10Y

,Player,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,...,2PM,2PP,FantPt,PPR,DKPt,FDPt,PosRank,N_PPR_OvRank,PPR_OvRank,Year
0,Jonathan Taylor,RB,22,17,17,0,0,0,0,0,...,0,0,333,373.1,381.1,353.1,1,5.0,5.0,2021
1,Cooper Kupp,WR,28,17,17,0,1,0,0,0,...,1,0,295,439.5,442.5,367.0,1,13.0,1.0,2021
2,Deebo Samuel,WR,25,16,15,1,2,24,1,0,...,0,0,262,339.0,347.0,300.5,2,16.0,9.0,2021
3,Josh Allen,QB,25,17,17,409,646,4407,36,15,...,2,1,403,402.6,426.6,417.6,1,1.0,2.0,2021
4,Austin Ekeler,RB,26,16,16,0,0,0,0,0,...,2,0,274,343.8,352.8,308.8,2,14.0,8.0,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5330,Dedrick Epps,TE,24,3,0,0,0,0,0,0,...,0,0,-1,-0.1,0.9,-0.6,115,517.0,518.0,2012
5331,Ted Ginn Jr.,WR,27,13,0,0,0,0,0,0,...,0,0,-1,0.8,1.8,-0.2,216,518.0,512.0,2012
5332,Brock Osweiler,QB,22,5,0,2,4,12,0,0,...,0,0,-1,-0.8,-0.8,-0.8,69,519.0,519.0,2012
5333,Graham Harrell,QB,27,4,0,2,4,20,0,0,...,0,0,-2,-1.5,-0.5,-1.5,70,520.0,520.0,2012
5334,Ryan Mallett,QB,24,4,0,1,4,17,0,1,...,0,0,-2,-2.2,-1.2,-1.2,72,521.0,521.0,2012

In [4]:
seasons_L10Y.dtypes

Player           object
FantPos          object
Age               int64
G                 int64
GS                int64
Cmp               int64
Att               int64
Yds               int64
TD                int64
Int               int64
Att.1             int64
Yds.1             int64
Y/A             float64
TD.1              int64
Tgt             float64
Rec               int64
Yds.2             int64
Y/R             float64
TD.2              int64
Fmb               int64
FL                int64
TD.3              int64
2PM               int64
2PP               int64
FantPt            int64
PPR             float64
DKPt            float64
FDPt            float64
PosRank           int64
N_PPR_OvRank    float64
PPR_OvRank      float64
Year              int64
dtype: object

In [5]:
seasons_L10Y.isnull().sum()

Player          0
FantPos         0
Age             0
G               0
GS              0
Cmp             0
Att             0
Yds             0
TD              0
Int             0
Att.1           0
Yds.1           0
Y/A             0
TD.1            0
Tgt             0
Rec             0
Yds.2           0
Y/R             0
TD.2            0
Fmb             0
FL              0
TD.3            0
2PM             0
2PP             0
FantPt          0
PPR             0
DKPt            0
FDPt            0
PosRank         0
N_PPR_OvRank    0
PPR_OvRank      0
Year            0
dtype: int64